Gobang@GameGobangAI@AIUserMain@MainGame@CurPlayerID int
Game@CurSpriteID int
Game@FormerId int
Game@FormerPosition int
Game@GridNum int
Game@InputPosition int
Game@MapSize int
Game@NextPlayerID int
Game@NextSpriteID int
Game@PlayerId int
Game@PlayerName string
Game@PlayerNumber int
Game@SpriteId int
Game@SpriteOwnerId int
Game@WithAI bool
Game@CurPlayerID int
Game@CurSpriteID int
Game@FormerId int
Game@FormerPosition int
Game@GridNum int
Game@InputPosition int
Game@MapSize int
Game@NextPlayerID int
Game@NextSpriteID int
Game@PlayerId int
Game@PlayerName string
Game@PlayerNumber int
Game@SpriteId int
Game@SpriteOwnerId int
Game@WithAI bool
Game@a int
Game@curr int
Game@t int
Main@GridNumber int
Main@MapS int
Main@GridNumber int
Main@InputPlayerNumber int
Main@MapS int
Main@GridNumber int
Main@InputPlayerId int
Main@InputPlayerName string
Main@InputPlayerNumber int
Main@InputWithAI bool
Main@MapS int
